### PR TITLE
check if validate apply v2 is enabled before running commands involving application deployments and releases

### PR DESCRIPTION
**Pull request by d-g-town**

### CODE REVIEW

**Review by ianedwards — APPROVED** [review]
Out of curiosity - were you able to determine that this is the exhaustive set of commands that'll be impacted?

**Comment by d-g-town** [comment]
> Out of curiosity - were you able to determine that this is the exhaustive set of commands that'll be impacted?

As best I can tell this is exhaustive: all the CLI commands use a helper function `checkLoginAndRun`, so I went through all the instances of this and checked whether the function works with application releases or not (if so, we will have to use new logic to do new deployments/get revision history).

**Review by stefanmcshane — APPROVED** [review]
Consider using the logger, instead of fmt.PrintX when writing outputs for a user

**Comment by d-g-town** [comment]
> Consider using the logger, instead of fmt.PrintX when writing outputs for a user

Looks like most of the existing CLI commands use color.New().  I'll look into refactoring all the print statements into a unified logger to pass around in coming PR.

**Pull request merged**
