### PR TITLE
Fix for issue with icons not showing up

### PR DESCRIPTION
**Pull request by jlorezz**

### CODE REVIEW

**Comment by Xetera** [comment]
Is it a good idea to be pulling things out of the `/wp-content/` of other sites? Seems like this site doesn't support serving images directly and prompt you to download them which might mean these endpoints can change at any time.

**Comment by jlorezz** [comment]
> Is it a good idea to be pulling things out of the `/wp-content/` of other sites? Seems like this site doesn't support serving images directly and prompts you to download them which might mean these endpoints can change at any time.

you are right. we could just host them our own with like imgur or something.

**Comment by jusrhee** [comment]
You can just put the files under `dashboard/src/assets` along with the other images

**Comment by jlorezz** [comment]
> You can just put the files under `/dashboard/src/assets` along with the other images

sounds good! will do that.

**Comment by jusrhee** [comment]
@jlorezz trying to review but could you pull from master - looks like your branch is nearly 1000 commits behind

**Comment by jlorezz** [comment]
> @jlorezz trying to review but could you pull from master - looks like your branch is nearly 1000 commits behind

will do! one second.

**Comment by jusrhee** [comment]
Great, thanks! Also, still not seeing an icon after linking up a DigitalOcean registry for some reason:
image

**Pull request closed without merging**
