### PR TITLE
[0.4.0] Support deployments from the CLI

### PR DESCRIPTION
**Pull request by abelanger5**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Users are unable to create new applications from the CLI, or update existing applications from the CLI. 

## What is the new behavior?

Create `porter create` and `porter deploy` endpoints that support new deployments from the CLI. Also supports build. 

## Technical Spec/Implementation Notes

<docs to come>

### CODE REVIEW

**Comment by jusrhee** [comment]
`porter config ...` command no longer exists - need to update docs elsewhere as well as on the dashboard.

**Comment by jusrhee** [comment]
image
image

Getting a 404 building from buildpack or Dockerfile (trying to push after the build process maybe). same repo works when linked from the dashboard with no additional configuration set

**Comment by abelanger5** [comment]
> Getting a 404 building from buildpack or Dockerfile (trying to push after the build process maybe). same repo works when linked from the dashboard with no additional configuration set

Just to be clear, are you running the local server and are you connected to it via `porter config set-host ...`?

**Comment by jusrhee** [comment]
> Just to be clear, are you running the local server and are you connected to it via porter config set-host ...?

Ah, thought it was just using existing endpoints and j calling from the CLI - will try again

**Review by jusrhee — APPROVED** [review]

**Pull request merged**
