### PR TITLE
[0.6.0] Fixes #911: it should be possible to regenerate webhooks

### LINKED ISSUE #911: Un-linking and re-linking a cluster removes the webhook secret
# Description

# Location

- [ ] Browser
- [ ] CLI
- [X] API

# Steps to reproduce

1. Link a cluster
2. Create a new deployment/release on that cluster
3. Un-link the cluster, and re-link it again
4. The webhook token was attached to the old cluster object, and thus will not be shown for the new cluster. 

# Additional Details

### PR DESCRIPTION
**Pull request by abelanger5**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [X] Other (please describe): make it possible to regenerate webhook URLs. 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] If it's a backend change, tests for the changes have been added and `go test ./...` runs successfully from the root folder.
- [ ] If it's a frontend change, Prettier has been run
- [ ] Docs have been reviewed and added / updated if needed

## What is the current behavior?

Issue Number: #911 

It is not currently possible to regenerate webhooks. 

## What is the new behavior?

When a webhook is not found for an web/worker/job chart, a button will be rendered on the frontend allowing you to generate a webhook URL for this web/worker/job. This will create a new webhook attached to that (name, namespace, clusterID) instance.

### CODE REVIEW

**Comment by jnfrati** [comment]
To replicate the issue locally, you have to go to the releases table and delete the chart you want to use as a test sample.

**Comment by igalakhov** [comment]
Working great for me @jnfrati! (tested by deleting releases, as you mentioned). One small thing is that I see the "Create Webhook" Button flashes for me when I switch tabs quickly:


https://user-images.githubusercontent.com/25856165/126843935-c6d6c62b-4936-4d96-b2c3-f529205ac42a.mov

**Comment by jnfrati** [comment]
> Working great for me @jnfrati! (tested by deleting releases, as you mentioned). One small thing is that I see the "Create Webhook" Button flashes for me when I switch tabs quickly:
> 

Fixed! Also added RBAC to the create webhook token button 👍

**Comment by angristan** [comment]
Thanks for this 👍

**Pull request merged**
